- name: Fail if import_dir is not defined
  ansible.builtin.fail:
    msg: "The variable 'import_dir' must be defined before running this task list."
  when: import_dir is not defined

- name: Copy data
  ansible.builtin.copy:
    src: "{{ ansible_data_dir }}/{{ data_tar }}"
    dest: "{{ import_dir }}/{{ data_tar }}"
    mode: "0644"

- name: Extract data
  ansible.builtin.shell: |
    tar --extract --use-compress-program=pigz \
    --file="{{ import_dir }}/{{ data_tar }}" \
    --directory="{{ import_dir }}"
    rm -f "{{ import_dir }}/{{ data_tar }}"
    chmod -R 0644 "{{ import_dir }}"
  args:
    executable: /bin/bash
  changed_when: true
