---
- name: Get query duration
  block:
  - name: Get duration from stderr
    ansible.builtin.set_fact:
      query_duration_ms: >-
        {{
          (
            query_execution.stderr_lines
            | select("match", "^DURATION_SECONDS=")
            | list
            | first
          )
          .split("=")[1]
          | float
        }}
    when: query_duration_ms is not defined and query_execution is defined

  - name: Convert duration to milliseconds
    ansible.builtin.set_fact:
     query_duration_ms: "{{ (query_duration_ms | float) * 1000 }}"

- name: Get rows read
  ansible.builtin.set_fact:
    rows_read: "NA"
  when: rows_read is not defined

- name: Get rows returned
  ansible.builtin.set_fact:
    rows_returned: "{{ query_rows_returned.stdout | string }}"
  when: rows_returned is not defined and query_rows_returned is defined

- name: Save result
  block:
    - name: Set local result fact on each host
      ansible.builtin.set_fact:
        local_result:
          test_type: "{{ test_type }}"
          host: "{{ inventory_hostname }}"
          start_datetime: "{{ start_datetime }}"
          end_datetime: "{{ end_datetime }}"
          query_duration_ms: "{{ query_duration_ms }}"
          rows_read: "{{ rows_read | default('NA') }}"
          rows_returned: "{{ rows_returned | default('0') }}"
          ram_limit: "{{ ram_limit | default('NA') }}"
          cpu_limit: "{{ cpu_limit | default('NA') }}"

    - name: Append this host’s result to NDJSON file
      delegate_to: localhost
      ansible.builtin.lineinfile:
        path: "{{ global_results_dir | default(project_root + '/results') }}/{{ test_type }}.ndjson"
        create: true
        insertafter: EOF
        line: "{{ local_result | to_json }}"
