---
- name: Configure VM
  include_tasks: "configure_vm.yml"
    
- name: Install and configure InfluxDB
  include_tasks: "install.yml"
   
- name: Generate InfluxDB token
  include_tasks: "generate_token.yml"

- name: Setup database
  include_tasks: "setup_database.yml"
   
- name: Import data into InfluxDB
  include_tasks: "import_data.yml"
    
- name: Verify data import
  include_tasks: "verify_import.yml"
