---
- name: Push and extract data
  ansible.builtin.unarchive:
    src: "{{ data_tar }}"
    dest: "/tmp/"
    mode: "0777"

- name: Import data
  ansible.builtin.shell: |
    /usr/bin/time -f "DURATION_SECONDS=%e" \
    mongoimport \
    --uri=mongodb://{{ login_host }}:{{ login_port }}/{{ login_db }} \
    --collection={{ collection }} \
    --file=/tmp/{{ data_file }}
  args:
    executable: /bin/bash
  register: insert_time
  changed_when: true

- name: Remove data file
  ansible.builtin.file:
    path: /tmp/{{ data_file }}
    state: absent