---
- name: Create database
  community.mongodb.mongodb_shell:
    login_host: "{{ db_host }}"
    login_port: "{{ db_port }}"
    db: "{{ db_database }}"
    eval: |
      db.createCollection('{{ db_table }}', {
        timeseries: {
          timeField: "GpsTime",
          metaField: "VehicleID",
          granularity: "seconds"
        }
      })