---
- name: Init OpenTSDB VM
  hosts: localhost
  vars_files:
    - /etc/ansible/host_vars/opentsdb.yml

  tasks:
    - name: Check if LXD VM exists
      ansible.builtin.command:
        cmd: "lxc info {{ vm_name }}"
      register: vm_state
      ignore_errors: true
      changed_when: false

    - name: Stop the VM
      ansible.builtin.command:
        cmd: "lxc stop {{ vm_name }} --force"
      when: vm_state.rc == 0
      ignore_errors: true
      changed_when: false

    - name: Delete LXD VM if it exists
      community.general.lxd_container:
        name: "{{ vm_name }}"
        state: absent
      when: vm_state.rc == 0

    - name: Launch LXD VM
      community.general.lxd_container:
        name: "{{ vm_name }}"
        type: "{{ lxd_type_base }}"
        state: started
        source:
          type: image
          mode: pull
          server: "{{ lxd_image_server_base }}"
          protocol: "{{ lxd_image_protocol_base }}"
          alias: "{{ lxd_image_base }}"
        profiles: "{{ vm_profiles }}"
        config: "{{ vm_config }}"
        devices: "{{ vm_devices }}"
        wait_for_ipv4_addresses: true
        timeout: 600

    - name: Wait for VM to initialize
      ansible.builtin.wait_for:
        timeout: 10

- name: Configure VM
  hosts: opentsdb
  tasks:
    - name: Create tmp directory
      ansible.builtin.file:
        path: "{{ ansible_remote_tmp }}"
        state: directory
        mode: "1777"

    - name: Update system packages
      ansible.builtin.apt:
        update_cache: true
        upgrade: dist
        cache_valid_time: "{{ apt_cache_valid_time_base }}"

    - name: Install packages
      ansible.builtin.apt:
        name: "{{ vm_packages }}"
        state: present
        update_cache: true
        cache_valid_time: "{{ apt_cache_valid_time_base }}"

    # - name: Configure swap file
    #   block:
    #     - name: Check if /swapfile is active swap
    #       ansible.builtin.command:
    #         cmd: "swapon --show=NAME --noheadings"
    #       register: swap_active
    #       changed_when: false

    #     - name: Allocate swap file (if not exists and not active)
    #       ansible.builtin.command:
    #         cmd: "fallocate -l {{ vm_swap_size }} /swapfile"
    #       args:
    #         creates: /swapfile
    #       when: "'/swapfile' not in swap_active.stdout"

    #     - name: Set permissions on swap file
    #       ansible.builtin.command:
    #         cmd: chmod 600 /swapfile
    #       when: "'/swapfile' not in swap_active.stdout"

    #     - name: Format swap (if not active)
    #       ansible.builtin.command:
    #         cmd: mkswap /swapfile
    #       when: "'/swapfile' not in swap_active.stdout"

    #     - name: Enable swap (if not active)
    #       ansible.builtin.command:
    #         cmd: swapon /swapfile
    #       when: "'/swapfile' not in swap_active.stdout"

    #     - name: Ensure swap entry exists in /etc/fstab
    #       ansible.builtin.lineinfile:
    #         path: /etc/fstab
    #         line: "/swapfile none swap sw 0 0"
    #         regexp: '^\s*/swapfile\s+'
    #         state: present
    #         insertafter: EOF

- name: Configure SSH for HBase
  hosts: opentsdb
  tasks:
    - name: Ensure .ssh directory exists
      ansible.builtin.file:
        path: "/root/.ssh"
        state: directory
        owner: root
        group: root
        mode: "0700"

    - name: Generate SSH key
      ansible.builtin.openssh_keypair:
        path: "/root/.ssh/id_rsa"
        size: 4096
        type: rsa
        owner: root
        group: root
        mode: "0600"
        force: false

    - name: Slurp remote root’s public key
      ansible.builtin.slurp:
        src: "/root/.ssh/id_rsa.pub"
      register: slurped_key

    - name: Add public key to authorized_keys
      ansible.builtin.authorized_key:
        user: root
        key: "{{ slurped_key.content | b64decode }}"
        state: present
        path: "/root/.ssh/authorized_keys"

    - name: Remove any existing 127.0.0.1 entry from known_hosts
      ansible.builtin.known_hosts:
        path: "/root/.ssh/known_hosts"
        name: 127.0.0.1
        state: absent

    - name: Disable strict host key checking
      ansible.builtin.blockinfile:
        path: "/root/.ssh/config"
        create: yes
        block: |
          Host 127.0.0.1
              StrictHostKeyChecking no
              UserKnownHostsFile=/dev/null
        owner: root
        group: root
        mode: "0600"

- name: Install and configure HBase
  hosts: opentsdb
  gather_facts: false
  tasks:
    - name: Download HBase
      ansible.builtin.get_url:
        url: "{{ hbase_tar_url }}"
        dest: /opt/hbase-{{ hbase_version }}-bin.tar.gz

    - name: Extract HBase
      ansible.builtin.unarchive:
        src: /opt/hbase-{{ hbase_version }}-bin.tar.gz
        dest: /opt
        remote_src: true

    - name: Create symbolic link
      ansible.builtin.file:
        src: /opt/hbase-{{ hbase_version }}
        dest: /hbase
        state: link

    - name: Clean up HBase archive
      ansible.builtin.file:
        path: /opt/hbase-{{ hbase_version }}-bin.tar.gz
        state: absent

    - name: Configure HBase environment exports
      ansible.builtin.lineinfile:
        path: /hbase/conf/hbase-env.sh
        regexp: "^#?export {{ item.key }}="
        line: "export {{ item.key }}={{ item.value }}"
        backrefs: no
      loop: "{{ hbase_env_settings | dict2items }}"

    - name: Enable distributed mode
      ansible.builtin.xml:
        path: /hbase/conf/hbase-site.xml
        xpath: '//property[name="hbase.cluster.distributed"]/value'
        value: "true"

    - name: Start HBase
      ansible.builtin.command:
        cmd: /hbase/bin/start-hbase.sh
        creates: /hbase/logs/hbase-root-master-opentsdb.log

- name: Install and configure OpenTSDB
  hosts: opentsdb
  gather_facts: false
  tasks:
    - name: Download OpenTSDB
      ansible.builtin.get_url:
        url: "{{ db_deb_url }}"
        dest: /opt/opentsdb-{{ db_version }}_all.deb

    - name: Install OpenTSDB
      ansible.builtin.apt:
        deb: /opt/opentsdb-{{ db_version }}_all.deb

    - name: Clean up OpenTSDB package
      ansible.builtin.file:
        path: /opt/opentsdb-{{ db_version }}_all.deb
        state: absent

    - name: Configure OpenTSDB settings
      ansible.builtin.lineinfile:
        path: /etc/opentsdb/opentsdb.conf
        regexp: "^{{ item.regex }}"
        line: "{{ item.line }}"
      loop:
        - {
            regex: '^#?\s*tsd\.core\.auto_create_metrics\s*=',
            line: "tsd.core.auto_create_metrics = true",
          }
        - {
            regex: '^#?\s*tsd\.core\.auto_create_tagks\s*=',
            line: "tsd.core.auto_create_tagks = true",
          }
        - {
            regex: '^#?\s*tsd\.core\.auto_create_tagvs\s*=',
            line: "tsd.core.auto_create_tagvs = true",
          }

    - name: Create OpenTSDB tables
      ansible.builtin.command: >
        env COMPRESSION=NONE HBASE_HOME=/hbase
        /usr/share/opentsdb/tools/create_table.sh
      changed_when: true

    - name: Start OpenTSDB service
      ansible.builtin.systemd:
        name: opentsdb
        state: started
        enabled: true

- name: Setup database and import data
  hosts: opentsdb
  gather_facts: false
  tasks:
    # - name: Push and extract data
    #   ansible.builtin.unarchive:
    #     src: "{{  ansible_data_dir }}/{{ data_tar }}"
    #     dest: "/tmp/"
    #     mode: "0777"

    - name: Push data
      ansible.builtin.copy:
        src: "{{ ansible_data_dir }}/{{ data_file }}"
        dest: "/tmp/"
        mode: "0777"

    - name: Split and compress data file
      ansible.builtin.shell: |
        set -euo pipefail
        exec > >(gzip > "/tmp/split_script.log.gz") 2>&1 
        n=1
        zcat "/tmp/{{ data_file }}" | while IFS= read -r line; do
          if [ $(( (i++) % {{ db_chunk_size }} )) -eq 0 ]; then
            [ -n "$out" ] && gzip -c > "$out"
            out="/tmp/{{ data_file | regex_replace('\.gz$', '') }}.$(printf "%03d" $n).gz"
            n=$((n+1))
          fi
          printf "%s\n" "$line" || exit 1
        done
        [ -n "$out" ] && gzip -c > "$out"
      args:
        executable: /bin/bash
        creates: "/tmp/{{ data_file | regex_replace('\\.gz$', '') }}.001.gz"

    - name: Clean up data
      ansible.builtin.file:
        path: "/tmp/{{ data_file }}"
        state: absent

    - name: find all the chunk files
      ansible.builtin.find:
        paths: /tmp
        patterns: "{{ data_file_name }}.*"
      register: chunk_files

    - name: import each chunk into OpenTSDB
      ansible.builtin.command:
        cmd: "/usr/share/opentsdb/bin/tsdb import {{ item.path }}"
      loop: "{{ chunk_files.files }}"
      loop_control:
        label: "{{ item.path }}"
      register: import_results
      retries: 3
      delay: 5
      until: import_results.rc == 0

    - name: remove temporary chunk files
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ chunk_files.files }}"
    # - name: Copy import script
    #   ansible.builtin.copy:
    #     src: "{{ ansible_scripts_dir }}/{{ script_file }}"
    #     dest: /tmp/{{ script_file }}
    #     mode: "0755"

    # - name: Create temporary directory
    #   ansible.builtin.file:
    #     path: "/tmp/tsdb_import/"
    #     state: directory
    #     mode: "0700"

    # - name: Split and import data in chunks via Python
    #   ansible.builtin.script:
    #     cmd: "{{ansible_scripts_dir}}/{{ script_file }} /tmp/{{ data_file }} {{ db_chunk_size }} /usr/share/opentsdb/bin/tsdb"
    #   args:
    #     executable: python3
    #   register: send_data_result
    #   changed_when: send_data_result.rc == 0
    #   failed_when: send_data_result.rc != 0

    # - name: Clean up temporary directory
    #   ansible.builtin.file:
    #     path: "{{ temp_dir }}"
    #     state: absent
    #   when: temp_dir is defined

- name: Verify data import
  hosts: opentsdb
  tasks:
    - name: Query total SumSalt
      ansible.builtin.shell: >
        /usr/share/opentsdb/bin/tsdb query
        2023/01/01-00:00:00
        2025/01/01-00:00:00
        sum {{ login_db }}.SumSalt |
        awk '{sum += $3} END {print sum}'
      register: query_result
      changed_when: false

    - name: Display result
      ansible.builtin.debug:
        msg: "{{ query_result.stdout }}"
# - name: Push data
#   ansible.builtin.copy:
#     src: "{{ ansible_data_dir }}/{{ data_file }}"
#     dest: "/tmp/"
#     mode: "0777"

# - name: Import data
#   ansible.builtin.command:
#     cmd: /usr/share/opentsdb/bin/tsdb import /tmp/{{ data_file }}
#   changed_when: true
