---
- name: Setup environment
  ansible.builtin.import_playbook: init_ansible_env.yml

- name: Initialize results system
  hosts: localhost
  tasks:
    - name: Check if results directory exists
      ansible.builtin.stat:
        path: "{{ project_root }}/results"
      register: results_dir_stat

    - name: Create results directory
      ansible.builtin.file:
        path: "{{ project_root }}/results"
        state: directory
        mode: "0755"
      when: not results_dir_stat.stat.exists
    
    - name: Set facts on hosts
      set_fact:
        global_results_dir: "{{ project_root }}/results"
        is_master_run: true
        test_type: "{{ test_type | default('insert') }}"
      delegate_to: "{{ item }}"
      delegate_facts: True
      loop: "{{ groups['databases'] }}"

- name: Run ClickHouse
  ansible.builtin.import_playbook: clickhousedb/init.yml
  ignore_errors: yes


- name: Run ColumnStore
  ansible.builtin.import_playbook: columnstoredb/init.yml
  ignore_errors: yes


- name: Run InfluxDB
  ansible.builtin.import_playbook: influxdb/init.yml
  ignore_errors: yes


- name: Run IoTDB
  ansible.builtin.import_playbook: iotdb/init.yml
  ignore_errors: yes


- name: Run MariaDB
  ansible.builtin.import_playbook: mariadb/init.yml
  ignore_errors: yes


- name: Run MongoDB
  ansible.builtin.import_playbook: mongodb/init.yml
  ignore_errors: yes

#- name: Run OpenTSDB
#  ansible.builtin.import_playbook: opentsdb/init.yml

- name: Run QuestDB
  ansible.builtin.import_playbook: questdb/init.yml
  ignore_errors: yes


- name: Run TimescaleDB
  ansible.builtin.import_playbook: timescaledb/init.yml
  ignore_errors: yes



