galaxy_info:
  author: Helmanz
  description: >
    Installs and configures ClickHouseDB on LXD-based virtual machines.
    Designed for Ubuntu 24.04 images deployed via LXD using the Simplestreams image server.
  license: MIT
  min_ansible_version: 2.16
  version: 1.0.0
  namespace: helmanz

  platforms:
    - name: Ubuntu
      versions:
        - 24.04

  galaxy_tags:
    - clickhouse
    - database
    - analytics
    - lxd
    - virtualization
    - ubuntu
    - monitoring

dependencies: []
