---
- name: Init QuestDB VM
  hosts: localhost
  vars_files:
    - /etc/ansible/host_vars/questdb.yml
  tasks:
    - name: Init VM
      ansible.builtin.include_tasks: "{{ common_dir }}/vm_init.yml"

- name: Common config
  hosts: questdb
  tasks:
    - name: Init VM
      ansible.builtin.include_tasks: "{{ common_dir }}/vm_config.yml"

- name: Install and configure QuestDB
  hosts: questdb
  tasks:
    - name: Download QuestDB
      ansible.builtin.get_url:
        url: "{{ db_tar_url }}"
        dest: /tmp/questdb.tar.gz
        mode: "0777"

    - name: Extract QuestDB
      ansible.builtin.unarchive:
        src: /tmp/questdb.tar.gz
        dest: /root/
        remote_src: true
        creates: /root/questdb

    - name: Rename QuestDB folder
      ansible.builtin.command:
        cmd: mv /root/questdb-{{  db_version }}-rt-linux-x86-64 /root/questdb
      args:
        removes: /root/questdb-{{ db_version }}-rt-linux-x86-64
        creates: /root/questdb

    - name: Clean up download
      ansible.builtin.file:
        path: /tmp/questdb.tar.gz
        state: absent

    - name: Start QuestDB service
      ansible.builtin.command:
        cmd: /root/questdb/bin/questdb.sh start
      changed_when: false

- name: Setup database and import data
  hosts: questdb
  tasks:
    - name: Create table
      community.postgresql.postgresql_query:
        query: >
          CREATE TABLE IF NOT EXISTS {{ collection }} (
            orig_id          INT,
            orig_time        TIMESTAMP,
            orig_topic       STRING,
            CreatedTime      TIMESTAMP,
            GpsTime          TIMESTAMP,
            GsmSignal        INT,
            SatelliteCount   INT,
            LicensePlate     STRING,
            VehicleType      INT,
            Company          STRING,
            VehicleID        INT,
            Technology       INT,
            Ignition         INT,
            Longitude        DOUBLE,
            Latitude         DOUBLE,
            SpeedGps         DOUBLE,
            SpeedTach        DOUBLE,
            SpeedCan         DOUBLE,
            TachoGps         DOUBLE,
            TachoTach        DOUBLE,
            ModeDrive        INT,
            SpreadingMode    INT,
            Plow             INT,
            Gram             INT,
            WidthLeft        DOUBLE,
            WidthRight       DOUBLE,
            SumSalt          DOUBLE,
            SumInert         DOUBLE,
            SumBrine         DOUBLE,
            Cuts1            INT,
            Cuts2            INT,
            Cuts3            INT,
            CentralBroom     INT,
            LeftBroom        INT,
            RightBroom       INT,
            Turbine          INT,
            RunningShaft     INT,
            LeftFlushing     INT,
            RightFlushing    INT,
            CentralFlushing  INT,
            Misting          INT,
            Pump             INT,
            LightOn          INT,
            ModeArrow        INT,
            AkuVoltage       DOUBLE,
            RampUp           INT,
            Crash            INT,
            TempAir          DOUBLE,
            TempRoad         DOUBLE,
            Revs             DOUBLE,
            RevsExtension    INT,
            Fuel             DOUBLE,
            LevelPHM         DOUBLE,
            PowerVoltage     DOUBLE,
            Lighthouse       INT
          ) TIMESTAMP(orig_time) PARTITION BY DAY;
        login_host: "{{ db_host }}"
        login_port: "{{ db_port }}"
        login_user: "{{ db_user }}"
        login_password: "{{ db_password }}"
        login_db: "{{ login_db }}"

    - name: Push and extract data
      ansible.builtin.unarchive:
        src: "{{  ansible_data_dir }}/{{ data_tar }}"
        dest: "/root/.questdb/import/"
        mode: "0777"

    - name: Import data
      community.postgresql.postgresql_query:
        query: >
          COPY {{ collection }}
          FROM '{{ data_file }}'
          WITH HEADER true
          TIMESTAMP 'orig_time'
        login_host: "{{ db_host }}"
        login_port: "{{ db_port }}"
        login_user: "{{ db_user }}"
        login_password: "{{ db_password }}"
        login_db: "{{ login_db }}"

    - name: Wait for import to finish
      community.postgresql.postgresql_query:
        query: SELECT COUNT(*) AS count FROM {{ collection }};
        login_host: "{{ db_host }}"
        login_port: "{{ db_port }}"
        login_user: "{{ db_user }}"
        login_password: "{{ db_password }}"
        login_db: "{{ login_db }}"
      register: result
      until: result.query_result[0].count | int >= 600000
      retries: "{{ db_import_retries }}"
      delay: "{{ db_import_retry_inverval }}"

    - name: Remove data file
      ansible.builtin.file:
        path: /root/.questdb/import/{{ data_file }}
        state: absent

- name: Verify data import
  hosts: questdb
  tasks:
    - name: Query total SumSalt
      community.postgresql.postgresql_query:
        query: SELECT sum(sumsalt) FROM {{ collection }};
        login_host: "{{ db_host }}"
        login_port: "{{ db_port }}"
        login_user: "{{ db_user }}"
        login_password: "{{ db_password }}"
        login_db: "{{ login_db }}"
      register: query_result

    - name: Capture result
      ansible.builtin.set_fact:
        result: "{{ query_result.query_result[0].sum | float }}"

    - name: Display result
      ansible.builtin.debug:
        msg: "{{ result }}"

- name: Post processing
  hosts: questdb
  tasks:
    - name: Common post processing
      ansible.builtin.include_tasks: "{{ common_dir }}/vm_post_processing.yml"
