---
- name: Push and extract data
  ansible.builtin.unarchive:
    src: "{{ data_tar }}"
    dest: "/tmp/"
    mode: "0777"

- name: Import data
  become: true
  become_user: "{{ db_user }}"
  ansible.builtin.shell: |
    /usr/bin/time -f "DURATION_SECONDS=%e" \
    psql -d {{ login_db }} -c "\
      COPY {{ collection }} FROM '/tmp/{{ data_file }}' WITH (FORMAT csv, HEADER true);\
    "
  args:
    executable: /bin/bash
  register: insert_time
  changed_when: true

- name: Remove data file
  ansible.builtin.file:
    path: /tmp/{{ data_file }}
    state: absent