---
- name: Install packages
  ansible.builtin.apt:
    name: "{{ vm_packages }}"
    cache_valid_time: "{{ apt_cache_valid_time_base }}"
    state: present
    update_cache: true
  when: vm_packages is defined and vm_packages | length > 0

- name: Download TimescaleDB GPG key
  ansible.builtin.apt_key:
    url: "{{ gpg_key_url }}"
    keyring: /usr/share/keyrings/timescaledb-archive-keyring.gpg
    state: present
    validate_certs: yes

- name: Gather distribution facts
  ansible.builtin.setup:
    gather_subset:
      - distribution

- name: Add TimescaleDB APT repository
  ansible.builtin.apt_repository:
    repo: >
      deb [signed-by=/usr/share/keyrings/timescaledb-archive-keyring.gpg]
      https://packagecloud.io/timescale/timescaledb/ubuntu/ {{ ansible_lsb.codename | lower }} main
    filename: timescaledb.list
    state: present
    update_cache: true
  register: repo_result
  retries: 5
  delay: 10
  until: repo_result is succeeded

- name: Add PostgreSQL repository
  ansible.builtin.command:
    cmd: /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh -y
  changed_when: true

- name: Install PostgreSQL dependencies
  ansible.builtin.apt:
    name: postgresql-server-dev-17
    state: present
    update_cache: true
  register: postgre_result
  retries: 5
  delay: 10
  until: postgre_result is succeeded

- name: Install TimescaleDB
  ansible.builtin.apt:
    name:
      - timescaledb-2-postgresql-17
      - postgresql-client-17
    state: present
    update_cache: true
  register: timescale_result
  retries: 5
  delay: 10
  until: timescale_result is succeeded

- name: Tune TimescaleDB configuration
  ansible.builtin.command:
    cmd: timescaledb-tune --yes
  changed_when: true

- name: Change local postgres auth method from peer to trust
  ansible.builtin.replace:
    path: /etc/postgresql/17/main/pg_hba.conf
    regexp: '^local\s+all\s+postgres\s+peer'
    replace: 'local   all             postgres                                trust'
    backup: true

- name: Configure PostgreSQL authentication
  ansible.builtin.replace:
    path: /etc/postgresql/17/main/pg_hba.conf
    regexp: "{{ item.regex }}"
    replace: "{{ item.replace }}"
    backup: true
  loop:
    - regex: '^local\s+all\s+all\s+peer'
      replace: "local all all trust"
    - regex: '^host\s+all\s+all\s+127\.0\.0\.1\/32\s+scram-sha-256'
      replace: "host all all 127.0.0.1/32 trust"
    - regex: '^host\s+all\s+all\s+::1\/128\s+scram-sha-256'
      replace: "host all all ::1/128 trust"
  loop_control:
    label: "{{ item.regex }}"
  tags:
    - postgresql

- name: Restart PostgreSQL
  ansible.builtin.systemd:
    name: postgresql
    state: restarted