---
# VM VARS
vm_name: columnstoredb
vm_packages: "{{ packages_base +
  [
  'python3-pymysql',
  'libjemalloc2'
  ]
  }}"
vm_config:
  limits.memory: "2GiB"
  limits.cpu: "1"

vm_devices:
  root:
    type: disk
    pool: default
    path: /
    size: 5GB

vm_profiles: "{{ lxd_profiles_base + ['columnstoredb-net'] }}"

vm_sysctl_params:
  - name: vm.swappiness
    value: "1"
  - name: net.core.rmem_max
    value: "16777216"
  - name: net.core.wmem_max
    value: "16777216"
  - name: net.ipv4.tcp_rmem
    value: "4096 87380 16777216"
  - name: net.ipv4.tcp_wmem
    value: "4096 65536 16777216"
  - name: net.ipv4.tcp_no_metrics_save
    value: "1"
  - name: net.core.netdev_max_backlog
    value: "2500"

# FILE VARS
data_file: "raltra.csv"
data_tar: "{{ data_file }}.tar.gz"
script_file: ""

# DB VARS
login_db: raltra
collection: car_telemetry
mariadb_version: "11.8.2"
db_apt_key: "https://mariadb.org/mariadb_release_signing_key.asc"
db_repo_url: "https://r.mariadb.com/downloads/mariadb_repo_setup"
db_checksum: "sha256:c4a0f3dade02c51a6a28ca3609a13d7a0f8910cccbb90935a2f218454d3a914a"
db_user_host:
  - "127.0.0.1"
  - "locahost"
db_cross_engine_config:
  - key: "CrossEngineSupport Host"
    value: "127.0.0.1"
  - key: "CrossEngineSupport Port"
    value: "3306"
  - key: "CrossEngineSupport User"
    value: "cross_engine"
  - key: "CrossEngineSupport Password"
    value: "cross_engine"
