---
# VM VARS
vm_name: influxdb
vm_packages: "{{ packages_base }}"

vm_disk_size: 8GB
vm_profiles: "{{ lxd_profiles_base + ['influxdb-net'] }}"

# FILE VARS
data_file_name: "raltra"
data_file: "raltra.lp"
data_tar: "{{ data_file }}.tar.gz"
script_file: "send_data.sh"

# DB VARS
db_host: localhost
db_port: 8181
db_tar_url: "https://dl.influxdata.com/influxdb/releases/influxdb3-core-3.0.3_linux_amd64.tar.gz"
login_db: raltra
db_table: car_telemetry
