---
# VM VARS
vm_name: opentsdb
vm_packages: "{{ packages_base +
  [
  'openjdk-8-jdk',
  'python3-lxml',
  'gnuplot'
  ]
  }}"

vm_disk_size: 16GB
vm_profiles: "{{ lxd_profiles_base + ['opentsdb-net'] }}"

vm_swap_size: "2G"

vm_openjdk_path: "/usr/lib/jvm/java-8-openjdk-amd64"

# FILE VARS
data_file_name: "raltra"
data_file: "raltra.txt"
data_tar: "raltra.txt.tar.gz"
script_file: "send_data.py"

# DB VARS
db_version: "2.4.1"
db_deb_url: "https://github.com/OpenTSDB/opentsdb/releases/download/v{{ db_version }}/opentsdb-{{ db_version }}_all.deb"
db_host: 127.0.0.1
db_port: 4242
login_db: raltra
collection: car_telemetry
db_chunk_size: 50000

# HBASE VARS
hbase_version: "2.5.12"
hbase_tar_url: "https://dlcdn.apache.org/hbase/{{ hbase_version }}/hbase-{{ hbase_version }}-bin.tar.gz"
hbase_heapsize: 2048
hbase_env_settings:
  JAVA_HOME: "{{ vm_openjdk_path }}"
  HBASE_HEAPSIZE: "{{ hbase_heapsize }}"
