---
# VM VARS
vm_name: questdb
vm_packages: "{{ packages_base +
  [
  'postgresql-client',
  'python3-psycopg2',
  'gnuplot'
  ]
  }}"
vm_config:
  limits.memory: "2GiB"
  limits.cpu: "1"

vm_devices:
  root:
    type: disk
    pool: default
    path: /
    size: 8GB

vm_profiles: "{{ lxd_profiles_base + ['questdb-net'] }}"

vm_swap_size: "2G"

vm_openjdk_path: "/usr/lib/jvm/java-8-openjdk-amd64"

# FILE VARS
data_file: "raltra.csv"
data_tar: "{{ data_file }}.tar.gz"
script_file: ""

# DB VARS
db_version: "8.3.3"
db_tar_url: "https://github.com/questdb/questdb/releases/download/{{ db_version }}/questdb-{{ db_version }}-rt-linux-x86-64.tar.gz"
db_port: 8812
db_host: localhost
db_user: admin
db_password: quest
db_import_retries: 300
db_import_retry_inverval: 10
login_db: qdb
collection: car_telemetry
