---
- name: Init ColumnstoreDB VM
  hosts: localhost
  vars_files:
    - "{{ ansible_vars_dir }}/host_vars/columnstoredb.yml"
  tasks:
    - name: Init VM
      ansible.builtin.include_tasks: "{{ ansible_common_dir }}/init/vm_init.yml"

- name: Common config
  hosts: columnstoredb
  tasks:
    - name: Init VM
      ansible.builtin.include_tasks: "{{ ansible_common_dir }}/init/vm_config.yml"

- name: Configure VM
  hosts: columnstoredb
  tasks:
    - name: Configure sysctl parameters
      ansible.builtin.copy:
        dest: /etc/sysctl.d/90-mariadb-columnstore.conf
        content: |
          # BEGIN ANSIBLE MANAGED BLOCK - SYSCTL PARAMETERS
          {% for item in vm_sysctl_params %}
          {{ item.name }} = {{ item.value }}
          {% endfor %}
          # END ANSIBLE MANAGED BLOCK - SYSCTL PARAMETERS

    - name: Apply sysctl settings
      ansible.builtin.sysctl:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        state: present
        reload: yes
        sysctl_set: yes
      loop: "{{ vm_sysctl_params }}"

    - name: Disable AppArmor
      ansible.builtin.systemd:
        name: apparmor
        state: stopped
        enabled: no

    - name: Configure locale
      ansible.builtin.command:
        cmd: localedef -i en_US -f UTF-8 en_US.UTF-8
      changed_when: true

    - name: Reboot VM to apply changes
      ansible.builtin.reboot:
        msg: "Rebooting after system configuration"
        connect_timeout: 30
        reboot_timeout: 300

- name: Install and configure MariaDB ColumnStore
  hosts: columnstoredb
  tasks:
    - name: Add MariaDB APT key
      ansible.builtin.apt_key:
        url: "{{ db_key_url }}"
        state: present
        validate_certs: true

    - name: Add MariaDB APT repository
      ansible.builtin.apt_repository:
        repo: >
          deb [arch=amd64]
          http://mirror.mariadb.org/repo/{{ db_version }}/ubuntu
          {{ ansible_distribution_release | lower }} main
        state: present
        filename: mariadb

    - name: Install MariaDB with ColumnStore
      ansible.builtin.apt:
        name:
          - mariadb-server
          - mariadb-backup
          - mariadb-client
          - mariadb-plugin-columnstore
        state: latest

    - name: Configure MariaDB basic settings
      ansible.builtin.copy:
        dest: /etc/mysql/mariadb.conf.d/90-columnstore.cnf
        content: |
          # BEGIN ANSIBLE MANAGED BLOCK - COLUMNSTORE PARAMETERS
          [mariadb]
          log_error = mariadbd.err
          character_set_server = utf8
          collation_server = utf8_general_ci
          # END ANSIBLE MANAGED BLOCK - COLUMNSTORE PARAMETERS

    - name: Set CrossEngineSupport configuration
      ansible.builtin.command:
        cmd: "mcsSetConfig {{ item.key }} {{ item.value }}"
      loop: "{{ db_cross_engine_config }}"

    - name: Start and enable MariaDB
      ansible.builtin.service:
        name: mariadb
        state: started
        enabled: true

    - name: Start and enable ColumnStore service
      ansible.builtin.service:
        name: mariadb-columnstore
        state: started
        enabled: true

- name: Setup database and import data
  hosts: columnstoredb
  vars:
    import_dir: "/tmp"
    socket: "/var/run/mysqld/mysqld.sock"
  tasks:
    - name: Create cross-engine user
      community.mysql.mysql_user:
        name: cross_engine
        password: cross_engine
        host: "{{ item }}"
        priv: "*.*:SELECT,PROCESS"
        state: present
        login_unix_socket: "{{ socket }}"
      loop: "{{ db_user_host }}"

    - name: Restart services
      ansible.builtin.service:
        name: "{{ item }}"
        state: restarted
      loop:
        - mariadb
        - mariadb-columnstore

    - name: Create database
      community.mysql.mysql_db:
        login_unix_socket: "{{ socket }}"
        name: "{{ login_db }}"
        state: present

    - name: Create ColumnStore table
      community.mysql.mysql_query:
        login_unix_socket: "{{ socket }}"
        query: |
          CREATE TABLE {{ login_db }}.{{ db_table }} (
            orig_id INT,
            orig_time DATETIME,
            orig_topic TINYTEXT,
            CreatedTime DATETIME,
            GpsTime DATETIME,
            GsmSignal SMALLINT UNSIGNED,
            SatelliteCount SMALLINT UNSIGNED,
            LicensePlate VARCHAR(10),
            VehicleType TINYINT UNSIGNED,
            Company VARCHAR(10),
            VehicleID INT UNSIGNED,
            Technology SMALLINT UNSIGNED,
            Ignition SMALLINT UNSIGNED,
            Longitude DECIMAL(14, 10),
            Latitude DECIMAL(14, 10),
            SpeedGps DECIMAL(9, 3),
            SpeedTach DECIMAL(9, 3),
            SpeedCan DECIMAL(9, 3),
            TachoGps DECIMAL(9, 3),
            TachoTach DECIMAL(9, 3),
            ModeDrive SMALLINT UNSIGNED,
            SpreadingMode SMALLINT UNSIGNED,
            Plow SMALLINT UNSIGNED,
            Gram BIGINT UNSIGNED,
            WidthLeft DECIMAL(9, 3),
            WidthRight DECIMAL(9, 3),
            SumSalt DECIMAL(18, 8) UNSIGNED,
            SumInert DECIMAL(18, 8) UNSIGNED,
            SumBrine DECIMAL(18, 8) UNSIGNED,
            Cuts1 SMALLINT UNSIGNED,
            Cuts2 SMALLINT UNSIGNED,
            Cuts3 SMALLINT UNSIGNED,
            CentralBroom SMALLINT UNSIGNED,
            LeftBroom SMALLINT UNSIGNED,
            RightBroom SMALLINT UNSIGNED,
            Turbine SMALLINT UNSIGNED,
            RunningShaft SMALLINT UNSIGNED,
            LeftFlushing SMALLINT UNSIGNED,
            RightFlushing SMALLINT UNSIGNED,
            CentralFlushing SMALLINT UNSIGNED,
            Misting SMALLINT UNSIGNED,
            Pump SMALLINT UNSIGNED,
            LightOn SMALLINT UNSIGNED,
            ModeArrow SMALLINT UNSIGNED,
            AkuVoltage DECIMAL(9, 3),
            RampUp SMALLINT UNSIGNED,
            Crash SMALLINT UNSIGNED,
            TempAir DECIMAL(9, 3),
            TempRoad DECIMAL(9, 3),
            Revs DECIMAL(18, 10) UNSIGNED,
            RevsExtension SMALLINT UNSIGNED,
            Fuel DECIMAL(9, 3),
            LevelPHM DECIMAL(9, 3),
            PowerVoltage DECIMAL(9, 3),
            Lighthouse SMALLINT UNSIGNED
          ) ENGINE=Columnstore

    - name: Copy data
      ansible.builtin.include_tasks: "{{ ansible_common_dir }}/init/vm_copy_data.yml"

    - name: Remove CSV header
      ansible.builtin.shell: |
        tail -n +2 {{ import_dir }}/{{ data_file }}> {{ import_dir }}/tmp.csv
        mv {{ import_dir }}/tmp.csv {{ import_dir }}/{{ data_file }}
      args:
        executable: /bin/bash

    - name: Import data
      ansible.builtin.shell: |
        /usr/bin/time -f "DURATION_SECONDS=%e" \
        cpimport -s ',' {{ login_db }} {{ db_table }} {{ import_dir }}/{{ data_file }}
      args:
        executable: /bin/bash
      register: insert_time
      changed_when: true

    - name: Remove data file
      ansible.builtin.file:
        path: "{{ import_dir }}/{{ data_file }}"
        state: absent

- name: Verify data import
  hosts: columnstoredb
  vars:
    socket: "/var/run/mysqld/mysqld.sock"
  tasks:
    - name: Query total SumSalt
      community.mysql.mysql_query:
        login_unix_socket: "{{ socket }}"
        login_db: "{{ login_db }}"
        query: "SELECT CAST(SUM(SumSalt) AS DOUBLE) AS TotalSalt FROM {{ db_table }};"
      register: query_result

    - name: Capture result
      ansible.builtin.set_fact:
        result: "{{ query_result.query_result[0][0]['TotalSalt'] | float }}"

    - name: Display result
      ansible.builtin.debug:
        msg: "{{ result }}"

- name: Post processing
  hosts: columnstoredb
  tasks:
    - name: Common post processing
      ansible.builtin.include_tasks: "{{ ansible_common_dir }}/init/vm_post_processing.yml"
