---
- name: Apply sysctl settings
  ansible.builtin.command: sysctl --system

- name: Restart services
  ansible.builtin.service:
    name: "{{ item }}"
    state: restarted
  loop:
    - mariadb
    - mariadb-columnstore
  listen: "Restart services"