---
- name: Check if LXD VM exists
  ansible.builtin.command:
    cmd: "lxc info {{ vm_name }}"
  register: vm_state
  failed_when: false
  changed_when: false

- name: Stop the VM
  ansible.builtin.command:
    cmd: "lxc stop {{ vm_name }} --force"
  when: vm_state.rc == 0
  failed_when: false
  changed_when: false

- name: Delete LXD VM if it exists
  community.general.lxd_container:
    name: "{{ vm_name }}"
    state: absent
  when: vm_state.rc == 0

- name: Launch LXD VM
  community.general.lxd_container:
    name: "{{ vm_name }}"
    type: "{{ lxd_type_base }}"
    state: started
    source:
      type: image
      mode: pull
      server: "{{ lxd_image_server_base }}"
      protocol: "{{ lxd_image_protocol_base }}"
      alias: "{{ lxd_image_base }}"
    profiles: "{{ vm_profiles }}"
    config: "{{ vm_config }}"
    devices: "{{ vm_devices }}"
    wait_for_ipv4_addresses: true
    timeout: 600

- name: Wait for VM init
  ansible.builtin.wait_for:
    timeout: 10
