---
lxd_container_type: "container"
lxd_image_src: "https://cloud-images.ubuntu.com/releases/"
lxd_image: "24.04"
lxd_profiles: ["default"]
lxd_wait_for_ipv4: true
lxd_timeout: 120

lxd_default_disk_size: "10GB"
lxd_container_devices:
  eth0:
    nictype: bridged
    parent: lxdbr0
    type: nic
    ipv4.address: "{{ vm_ip }}"
  root:
    type: disk
    pool: default
    path: /
    size: "{{ vm_disk_size }}"

lxd_ssh_timeout: 90

shared_packages:
  - python3
  - gnupg
  - curl
  - micro
  - python3-pip
  - tar
  - wget
  - pigz
  - sudo
  - acpid