---
- name: Install Prometheus
  ansible.builtin.include_tasks: install_prometheus.yml

- name: Install Grafana
  ansible.builtin.include_tasks: install_grafana.yml

- name: Configure Grafana provisioning
  ansible.builtin.include_tasks: configure_grafana.yml