---
lxd_image_base: "24.04"
lxd_profiles_base: ["default", "ssh-password"]
lxd_type_base: virtual-machine
lxd_image_server_base: https://cloud-images.ubuntu.com/releases/
lxd_image_protocol_base: simplestreams
packages_base:
  - python3
  - gnupg
  - curl
  - micro
  - python3-pip
  - tar
  - wget
  - pigz
apt_cache_valid_time_base: 3600

project_root: "{{ lookup('env', 'PROJECT_ROOT') | default(lookup('env', 'HOME') + '/playbook', true) }}"

ansible_data_dir: "{{ project_root }}/{{ inventory_hostname }}/data"
ansible_scripts_dir: "{{ project_root }}/{{ inventory_hostname }}/scripts"
ansible_common_dir: "{{ project_root }}/common"
ansible_vars_dir: "{{ project_root }}/vars"
ansible_resources_dir: "{{ ansible_vars_dir }}/resource_vars"
ansible_helper_dir: "{{ project_root }}/{{ inventory_hostname }}/helper"
ansible_env_file: "{{ project_root }}/.env"

ansible_user: root
ansible_connection: community.general.lxd
ansible_remote_tmp: /tmp/ansible-$USER

default_ram_profile: "ram2"
default_cpu_profile: "cpu1"

data_file_name: "{{ data_file.split('.')[0] }}"
data_tar: "{{ data_file }}.tar.gz"
data_gz: "{{ data_file }}.gz"
data_zip: "{{ data_file }}.zip"
