---
- name: Import data
  ansible.builtin.shell: |
    /usr/bin/time -f "DURATION_SECONDS=%e" \
    python3 "/tmp/{{ script_file }}" "{{ temp_dir }}"
  args:
    executable: /bin/bash
  register: insert_time
  changed_when: true

# - name: Upload chunks using Python script
#   ansible.builtin.script:
#     cmd: "{{ ansible_scripts_dir }}/{{ script_file }} {{ temp_dir }}"
#   args:
#     executable: python3

- name: Clean up data
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "/tmp/{{ data_file }}"
    - "{{ temp_dir }}"