---
- name: Download OpenTSDB
  ansible.builtin.get_url:
    url: "{{ db_deb_url }}"
    dest: /opt/opentsdb-{{ db_version }}_all.deb

- name: Install OpenTSDB
  ansible.builtin.apt:
    deb: /opt/opentsdb-{{ db_version }}_all.deb

- name: Clean up OpenTSDB package
  ansible.builtin.file:
    path: /opt/opentsdb-{{ db_version }}_all.deb
    state: absent

- name: Configure OpenTSDB settings
  ansible.builtin.lineinfile:
    path: /etc/opentsdb/opentsdb.conf
    regexp: "^{{ item.regex }}"
    line: "{{ item.line }}"
  loop:
    - {
        regex: '^#?\s*tsd\.core\.auto_create_metrics\s*=',
        line: "tsd.core.auto_create_metrics = true",
      }
    - {
        regex: '^#?\s*tsd\.core\.auto_create_tagks\s*=',
        line: "tsd.core.auto_create_tagks = true",
      }
    - {
        regex: '^#?\s*tsd\.core\.auto_create_tagvs\s*=',
        line: "tsd.core.auto_create_tagvs = true",
      }
    - {
        regex: '^#?\s*tsd\.http\.request\.enable_chunked\s*=',
        line: "tsd.http.request.enable_chunked = true",
      }
    - {
        regex: '^#?\s*tsd\.http\.request\.max_chunk\s*=',
        line: "tsd.http.request.max_chunk = 1073741824",
      }

- name: Create OpenTSDB tables
  ansible.builtin.command: >
    env COMPRESSION=NONE HBASE_HOME=/hbase
    /usr/share/opentsdb/tools/create_table.sh
  changed_when: true

- name: Start OpenTSDB service
  ansible.builtin.systemd:
    name: opentsdb
    state: started
    enabled: true