---
- name: Download HBase
  ansible.builtin.get_url:
    url: "{{ hbase_tar_url }}"
    dest: /opt/hbase-{{ hbase_version }}-bin.tar.gz

- name: Extract HBase
  ansible.builtin.unarchive:
    src: /opt/hbase-{{ hbase_version }}-bin.tar.gz
    dest: /opt
    remote_src: true

- name: Create symbolic link
  ansible.builtin.file:
    src: /opt/hbase-{{ hbase_version }}
    dest: /hbase
    state: link

- name: Clean up HBase archive
  ansible.builtin.file:
    path: /opt/hbase-{{ hbase_version }}-bin.tar.gz
    state: absent

- name: Configure HBase environment exports
  ansible.builtin.lineinfile:
    path: /hbase/conf/hbase-env.sh
    regexp: "^#?export {{ item.key }}="
    line: "export {{ item.key }}={{ item.value }}"
    backrefs: no
  loop: "{{ hbase_env_settings | dict2items }}"

- name: Enable distributed mode
  ansible.builtin.xml:
    path: /hbase/conf/hbase-site.xml
    xpath: '//property[name="hbase.cluster.distributed"]/value'
    value: "true"

- name: Start HBase
  ansible.builtin.command:
    cmd: /hbase/bin/start-hbase.sh
    creates: /hbase/logs/hbase-root-master-opentsdb.log

- name: Check HBase master status
  ansible.builtin.command:
    cmd: /hbase/bin/hbase shell -n
  args:
    stdin: "status\n"
  register: hbase_status

- name: Wait until HBase master is active
  ansible.builtin.wait_for:
    timeout: 60
  until: hbase_status.stdout is search('active master')
  retries: 20
  delay: 5