---
- name: Configure SSH for HBase
  ansible.builtin.include_tasks: "hbase_ssh.yml"
    
- name: Install and configure HBase
  ansible.builtin.include_tasks: "install_hbase.yml"

- name: Install and configure OpenTSDB
  ansible.builtin.include_tasks: "install_opentsdb.yml"
    
- name: Setup database
  ansible.builtin.include_tasks: "setup_database.yml"

- name: Import data into OpenTSDB
  ansible.builtin.include_tasks: "import_data.yml"

- name: Verify data import
  ansible.builtin.include_tasks: "verify_import.yml"
