---
- name: Push and extract data
  ansible.builtin.unarchive:
    src: "{{ data_tar }}"
    dest: "/tmp/"
    mode: "0777"

- name: Copy importing script
  ansible.builtin.copy:
    src: "{{ script_file }}"
    dest: "/tmp/"
    mode: "0777"

- name: Create chunk directory
  ansible.builtin.file:
    path: "{{ temp_dir }}"
    state: directory

- name: Split and compress file into chunks
  ansible.builtin.shell: |
    split -C 100M /tmp/{{ data_file }} {{ temp_dir }}/chunk_
    pigz {{ temp_dir }}/chunk_*
  args:
    executable: /bin/bash
