---
- name: Query total SumSalt
  ansible.builtin.shell: >
    /usr/share/opentsdb/bin/tsdb query
    2023/01/01-00:00:00
    2025/01/01-00:00:00
    sum {{ login_db }}.SumSalt |
    awk '{sum += $3} END {print sum}'
  register: query_result
  changed_when: false

- name: Capture result
  ansible.builtin.set_fact:
    result: "{{ query_result.stdout }}"

- name: Display total SumSalt
  ansible.builtin.debug:
    msg: "{{ result }}"