---
- name: Copy data
  ansible.builtin.copy:
    src: "{{ data_tar }}"
    dest: "{{ import_dir }}/{{ data_tar }}"
    mode: "0777"

- name: Extract data
  ansible.builtin.shell: |
    tar --extract --use-compress-program=pigz \
    --file="{{ import_dir }}/{{ data_tar }}" \
    --directory="{{ import_dir }}"
    rm -f "{{ import_dir }}/{{ data_tar }}"
    chmod -R 0777 "{{ import_dir }}"
  args:
    executable: /bin/bash
  changed_when: true

- name: Disable keys
  ansible.builtin.shell: |
    mysql {{ login_db }} -S {{ socket }} -e "ALTER TABLE {{ collection }} DISABLE KEYS;"
  args:
    executable: /bin/bash
  changed_when: false

- name: Import data
  ansible.builtin.shell: |
    /usr/bin/time -f "DURATION_SECONDS=%e" \
    mysql {{ login_db }} -S {{ socket }} -e "
    LOAD DATA INFILE '{{ import_dir }}/{{ data_file }}'
    INTO TABLE {{ collection }}
    FIELDS TERMINATED BY ',' ENCLOSED BY '\"' 
    LINES TERMINATED BY '\n' 
    IGNORE 1 ROWS
    (
        orig_id,
        @orig_time,
        orig_topic,
        @CreatedTime,
        @GpsTime,
        GsmSignal,
        SatelliteCount,
        LicensePlate,
        VehicleType,
        Company,
        VehicleID,
        Technology,
        Ignition,
        Longitude,
        Latitude,
        SpeedGps,
        SpeedTach,
        SpeedCan,
        TachoGps,
        TachoTach,
        ModeDrive,
        SpreadingMode,
        Plow,
        Gram,
        WidthLeft,
        WidthRight,
        SumSalt,
        SumInert,
        SumBrine,
        Cuts1,
        Cuts2,
        Cuts3,
        CentralBroom,
        LeftBroom,
        RightBroom,
        Turbine,
        RunningShaft,
        LeftFlushing,
        RightFlushing,
        CentralFlushing,
        Misting,
        Pump,
        LightOn,
        ModeArrow,
        AkuVoltage,
        RampUp,
        Crash,
        TempAir,
        TempRoad,
        Revs,
        RevsExtension,
        Fuel,
        LevelPHM,
        PowerVoltage,
        Lighthouse
    )
    SET
        orig_time   = STR_TO_DATE(@orig_time, '%Y-%m-%dT%H:%i:%s.%f'),
        CreatedTime = STR_TO_DATE(@CreatedTime, '%Y-%m-%dT%H:%i:%s.%f'),
        GpsTime     = STR_TO_DATE(@GpsTime, '%Y-%m-%dT%H:%i:%s.%f');"
  args:
    executable: /bin/bash
  register: insert_time
  changed_when: true

- name: Enable keys
  ansible.builtin.shell: |
    mysql {{ login_db }} -S {{ socket }} -e "ALTER TABLE {{ collection }} ENABLE KEYS;"
  args:
    executable: /bin/bash
  changed_when: false

- name: Remove data file
  ansible.builtin.file:
    path: /var/lib/mysql-files/{{ data_file }}
    state: absent