---
- name: Query total SumSalt
  community.mysql.mysql_query:
    login_unix_socket: "{{ socket }}"
    login_db: "{{ login_db }}"
    query: "SELECT CAST(SUM(SumSalt * 1.0) AS DOUBLE) AS TotalSalt FROM {{ collection }};"
  register: query_result

- name: Capture result
  ansible.builtin.set_fact:
    result: "{{ query_result.query_result[0][0]['TotalSalt'] | float }}"

- name: Display total SumSalt
  ansible.builtin.debug:
    msg: "{{ result }}"