---
# VM VARS
vm_name: columnstoredb
vm_packages: 
  - python3-pymysql
  - libjemalloc2

vm_disk_size: 8GB
vm_profiles: "{{ lxd_profiles_base }}"

# FILE VARS
data_file: "raltra.csv"

# DB VARS
db_user: cross_engine
db_password: cross_engine
db_privelages: "*.*:SELECT,PROCESS"

db_user_allowed_hosts:
  - "127.0.0.1"
  - "localhost"

db_database: raltra
db_table: car_telemetry

db_version: "11.8"

db_host: localhost
db_port: 3306
db_key_url: "https://mariadb.org/mariadb_release_signing_key.asc"
db_download_url: "https://r.mariadb.com/downloads/mariadb_repo_setup"
db_checksum: "sha256:c4a0f3dade02c51a6a28ca3609a13d7a0f8910cccbb90935a2f218454d3a914a"

