---
- name: Init MongoDB VM
  hosts: localhost
  vars_files:
    - "{{ ansible_vars_dir }}/host_vars/mongodb.yml"
  tasks:
    - name: Init VM
      ansible.builtin.include_tasks: "{{ ansible_common_dir }}/init/vm_init.yml"

- name: Common config
  hosts: mongodb
  tasks:
    - name: Common VM Config
      ansible.builtin.include_tasks: "{{ ansible_common_dir }}/init/vm_config.yml"

- name: Install and configure MongoDB
  hosts: mongodb
  tasks:
    - name: Download GPG key
      ansible.builtin.apt_key:
        url: "{{ gpg_key_url }}"
        keyring: /usr/share/keyrings/mongodb-server-8.0.gpg
        state: present
        validate_certs: yes

    - name: Add repository
      ansible.builtin.apt_repository:
        repo: >
          deb [arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-8.0.gpg]
          https://repo.mongodb.org/apt/ubuntu 
          {{ ansible_distribution_release | lower }}/mongodb-org/8.0 
          multiverse
        filename: mongodb-org-8.0.list
        update_cache: true
      # ansible-lint: disable=line-length

    - name: Install MongoDB
      ansible.builtin.apt:
        name: 
          - mongodb-org
          - mongodb-mongosh
        update_cache: true
      environment:
        DEBIAN_FRONTEND: noninteractive

    - name: Start MongoDB service
      ansible.builtin.service:
        name: mongod
        state: started
        enabled: true

- name: Setup database and import data
  hosts: mongodb
  tasks:
    - name: Create database
      community.mongodb.mongodb_shell:
        login_host: "{{ login_host }}"
        login_port: "{{ login_port }}"
        db: "{{ login_db }}"
        eval: |
          db.createCollection('{{ collection }}', {
            timeseries: {
              timeField: "GpsTime",
              metaField: "VehicleID",
              granularity: "seconds"
            }
          })

    - name: Push and extract data
      ansible.builtin.unarchive:
        src: "{{ ansible_data_dir }}/{{ data_tar }}"
        dest: "/tmp/"
        mode: "0777"

    - name: Import data
      ansible.builtin.shell: |
        /usr/bin/time -f "DURATION_SECONDS=%e" \
        mongoimport \
        --uri=mongodb://{{ login_host }}:{{ login_port }}/{{ login_db }} \
        --collection={{ collection }} \
        --file=/tmp/{{ data_file }}
      args:
        executable: /bin/bash
      register: insert_time
      changed_when: true

    - name: Remove data file
      ansible.builtin.file:
        path: /tmp/{{ data_file }}
        state: absent

- name: Verify data import
  hosts: mongodb
  tasks:
    - name: Query total SumSalt
      community.mongodb.mongodb_shell:
        login_host: "{{ login_host }}"
        login_port: "{{ login_port }}"
        db: "{{ login_db }}"
        eval: |
          db.{{ collection }}.aggregate([
            {
              $group: {
                _id: null,
                totalSumSalt: { $sum: "$SumSalt" }
              }
            }
          ]).toArray()
        transform: json
      register: query_result
      changed_when: false

    - name: Capture result
      ansible.builtin.set_fact:
        result: "{{ query_result.transformed_output[0].totalSumSalt }}"

    - name: Display result
      ansible.builtin.debug:
        msg: "{{ result }}"

- name: Post processing
  hosts: mongodb
  tasks:
    - name: Common post processing
      ansible.builtin.include_tasks: "{{ ansible_common_dir }}/init/vm_post_processing.yml"
