galaxy_info:
  author: Helmanz
  description: >
    Installs node_exporter on LXD-based VMs to expose system metrics for Prometheus scraping.
  license: MIT
  min_ansible_version: 2.16
  version: 1.0.0
  namespace: helmanz

  platforms:
    - name: Ubuntu
      versions:
        - 24.04

  galaxy_tags:
    - node_exporter
    - prometheus
    - monitoring
    - lxd
    - ubuntu

dependencies: []
