---
- name: Run ClickHouse
  import_playbook: clickhousedb/init.yml
  vars:
    results_dir: "{{ global_results_dir }}"
    is_master_run: "{{ is_master_run | default(false) }}"

- name: Run ColumnStore
  import_playbook: columnstoredb/init.yml
  vars:
    results_dir: "{{ global_results_dir }}"
    is_master_run: "{{ is_master_run | default(false) }}"

- name: Run InfluxDB
  import_playbook: influxdb/init.yml
  vars:
    results_dir: "{{ global_results_dir }}"
    is_master_run: "{{ is_master_run | default(false) }}"

- name: Run IoTDB
  import_playbook: iotdb/init.yml
  vars:
    results_dir: "{{ global_results_dir }}"
    is_master_run: "{{ is_master_run | default(false) }}"

- name: Run MariaDB
  import_playbook: mariadb/init.yml
  vars:
    results_dir: "{{ global_results_dir }}"
    is_master_run: "{{ is_master_run | default(false) }}"

- name: Run MongoDB
  import_playbook: mongodb/init.yml
  vars:
    results_dir: "{{ global_results_dir }}"
    is_master_run: "{{ is_master_run | default(false) }}"

- name: Run OpenTSDB
  import_playbook: opentsdb/init.yml
  vars:
    results_dir: "{{ global_results_dir }}"
    is_master_run: "{{ is_master_run | default(false) }}"

- name: Run QuestDB
  import_playbook: questdb/init.yml
  vars:
    results_dir: "{{ global_results_dir }}"
    is_master_run: "{{ is_master_run | default(false) }}"

- name: Run TimescaleDB
  import_playbook: timescaledb/init.yml
  vars:
    results_dir: "{{ global_results_dir }}"
    is_master_run: "{{ is_master_run | default(false) }}"
