---
- name: Init OpenTSDB VM
  hosts: localhost
  vars_files:
    - /etc/ansible/host_vars/opentsdb.yml
  tasks:
    - name: Init VM
      ansible.builtin.include_tasks: "{{ common_dir }}/vm_init.yml"

- name: Common config
  hosts: opentsdb
  tasks:
    - name: Init VM
      ansible.builtin.include_tasks: "{{ common_dir }}/vm_config.yml"

- name: Configure SSH for HBase
  hosts: opentsdb
  tasks:
    - name: Ensure .ssh directory exists
      ansible.builtin.file:
        path: "/root/.ssh"
        state: directory
        owner: root
        group: root
        mode: "0700"

    - name: Generate SSH key
      ansible.builtin.openssh_keypair:
        path: "/root/.ssh/id_rsa"
        size: 4096
        type: rsa
        owner: root
        group: root
        mode: "0600"
        force: false

    - name: Slurp remote root’s public key
      ansible.builtin.slurp:
        src: "/root/.ssh/id_rsa.pub"
      register: slurped_key

    - name: Add public key to authorized_keys
      ansible.builtin.authorized_key:
        user: root
        key: "{{ slurped_key.content | b64decode }}"
        state: present
        path: "/root/.ssh/authorized_keys"

    - name: Remove any existing 127.0.0.1 entry from known_hosts
      ansible.builtin.known_hosts:
        path: "/root/.ssh/known_hosts"
        name: 127.0.0.1
        state: absent

    - name: Disable strict host key checking
      ansible.builtin.blockinfile:
        path: "/root/.ssh/config"
        create: yes
        block: |
          Host 127.0.0.1
              StrictHostKeyChecking no
              UserKnownHostsFile=/dev/null
        owner: root
        group: root
        mode: "0600"

- name: Install and configure HBase
  hosts: opentsdb
  gather_facts: false
  tasks:
    - name: Download HBase
      ansible.builtin.get_url:
        url: "{{ hbase_tar_url }}"
        dest: /opt/hbase-{{ hbase_version }}-bin.tar.gz

    - name: Extract HBase
      ansible.builtin.unarchive:
        src: /opt/hbase-{{ hbase_version }}-bin.tar.gz
        dest: /opt
        remote_src: true

    - name: Create symbolic link
      ansible.builtin.file:
        src: /opt/hbase-{{ hbase_version }}
        dest: /hbase
        state: link

    - name: Clean up HBase archive
      ansible.builtin.file:
        path: /opt/hbase-{{ hbase_version }}-bin.tar.gz
        state: absent

    - name: Configure HBase environment exports
      ansible.builtin.lineinfile:
        path: /hbase/conf/hbase-env.sh
        regexp: "^#?export {{ item.key }}="
        line: "export {{ item.key }}={{ item.value }}"
        backrefs: no
      loop: "{{ hbase_env_settings | dict2items }}"

    - name: Enable distributed mode
      ansible.builtin.xml:
        path: /hbase/conf/hbase-site.xml
        xpath: '//property[name="hbase.cluster.distributed"]/value'
        value: "true"

    - name: Start HBase
      ansible.builtin.command:
        cmd: /hbase/bin/start-hbase.sh
        creates: /hbase/logs/hbase-root-master-opentsdb.log

- name: Install and configure OpenTSDB
  hosts: opentsdb
  gather_facts: false
  tasks:
    - name: Download OpenTSDB
      ansible.builtin.get_url:
        url: "{{ db_deb_url }}"
        dest: /opt/opentsdb-{{ db_version }}_all.deb

    - name: Install OpenTSDB
      ansible.builtin.apt:
        deb: /opt/opentsdb-{{ db_version }}_all.deb

    - name: Clean up OpenTSDB package
      ansible.builtin.file:
        path: /opt/opentsdb-{{ db_version }}_all.deb
        state: absent

    - name: Configure OpenTSDB settings
      ansible.builtin.lineinfile:
        path: /etc/opentsdb/opentsdb.conf
        regexp: "^{{ item.regex }}"
        line: "{{ item.line }}"
      loop:
        - {
            regex: '^#?\s*tsd\.core\.auto_create_metrics\s*=',
            line: "tsd.core.auto_create_metrics = true",
          }
        - {
            regex: '^#?\s*tsd\.core\.auto_create_tagks\s*=',
            line: "tsd.core.auto_create_tagks = true",
          }
        - {
            regex: '^#?\s*tsd\.core\.auto_create_tagvs\s*=',
            line: "tsd.core.auto_create_tagvs = true",
          }
        - {
            regex: '^#?\s*tsd\.http\.request\.enable_chunked\s*=',
            line: "tsd.http.request.enable_chunked = true",
          }
        - {
            regex: '^#?\s*tsd\.http\.request\.max_chunk\s*=',
            line: "tsd.http.request.max_chunk = 1073741824",
          }

    - name: Create OpenTSDB tables
      ansible.builtin.command: >
        env COMPRESSION=NONE HBASE_HOME=/hbase
        /usr/share/opentsdb/tools/create_table.sh
      changed_when: true

    - name: Start OpenTSDB service
      ansible.builtin.systemd:
        name: opentsdb
        state: started
        enabled: true

- name: Setup database and import data
  hosts: opentsdb
  vars:
    temp_dir: "/tmp/{{ data_file_name }}_temp"
  tasks:
    - name: Push and extract data
      ansible.builtin.unarchive:
        src: "{{ ansible_data_dir }}/{{ data_tar }}"
        dest: "/tmp/"
        mode: "0777"

    - name: Copy importing script
      ansible.builtin.copy:
        src: "{{ ansible_scripts_dir }}/{{ script_file }}"
        dest: "/tmp/"
        mode: "0777"

    - name: Create chunk directory
      ansible.builtin.file:
        path: "{{ temp_dir }}"
        state: directory

    - name: Split and compress file into chunks
      ansible.builtin.shell: |
        split -C 100M /tmp/{{ data_file }} {{ temp_dir }}/chunk_
        pigz {{ temp_dir }}/chunk_*
      args:
        executable: /bin/bash

    - name: Import data
      ansible.builtin.shell: |
        /usr/bin/time -f "DURATION_SECONDS=%e" \
        python3 "/tmp/{{ script_file }}" "{{ temp_dir }}"
      args:
        executable: /bin/bash
      register: insert_time
      changed_when: true

    # - name: Upload chunks using Python script
    #   ansible.builtin.script:
    #     cmd: "{{ ansible_scripts_dir }}/{{ script_file }} {{ temp_dir }}"
    #   args:
    #     executable: python3

    - name: Clean up data
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - "/tmp/{{ data_file }}"
        - "{{ temp_dir }}"

- name: Verify data import
  hosts: opentsdb
  tasks:
    - name: Query total SumSalt
      ansible.builtin.shell: >
        /usr/share/opentsdb/bin/tsdb query
        2023/01/01-00:00:00
        2025/01/01-00:00:00
        sum {{ login_db }}.SumSalt |
        awk '{sum += $3} END {print sum}'
      register: query_result
      changed_when: false

    - name: Capture result
      ansible.builtin.set_fact:
        result: "{{ query_result.stdout }}"

    - name: Display total SumSalt
      ansible.builtin.debug:
        msg: "{{ result }}"

- name: Post processing
  hosts: opentsdb
  tasks:
    - name: Common post processing
      ansible.builtin.include_tasks: "{{ common_dir }}/vm_post_processing.yml"
