---
- name: Init ClickHouse VM
  hosts: localhost
  vars_files:
    - "{{ ansible_vars_dir }}/host_vars/clickhousedb.yml"
  tasks:
    - name: Init VM
      ansible.builtin.include_tasks: "{{ ansible_common_dir }}/init/vm_init.yml"

- name: Common config
  hosts: clickhousedb
  tasks:
    - name: Common VM Config
      ansible.builtin.include_tasks: "{{ ansible_common_dir }}/init/vm_config.yml"

- name: "Install and configure ClickHouseDB"
  hosts: clickhousedb
  vars:
    keyring: "/usr/share/keyrings/clickhouse-keyring.gpg"
  tasks:
    - name: Download GPG key
      ansible.builtin.apt_key:
        url: "{{ db_key_url }}"
        keyring: "{{ keyring }}"
        state: present
        validate_certs: true

    - name: Add repository
      ansible.builtin.apt_repository:
        repo: >
          deb [signed-by={{ keyring }}
               arch=amd64]
          https://packages.clickhouse.com/deb lts main
        filename: clickhouse

    - name: Install ClickHouse
      ansible.builtin.apt:
        name:
          - clickhouse-server
          - clickhouse-client
      environment:
        DEBIAN_FRONTEND: noninteractive

    - name: Start ClickHouse service
      ansible.builtin.service:
        name: clickhouse-server
        state: started
        enabled: true

- name: Setup database and import data
  hosts: clickhousedb
  vars:
    import_dir: "/var/lib/clickhouse/user_files"
  tasks:
    - name: Create table structure
      ansible.builtin.shell: |
        clickhouse-client --query="
        CREATE TABLE IF NOT EXISTS {{ db_table }}
        (
            orig_id          Int32,
            orig_time        DateTime64(9, 'Europe/Prague'),
            orig_topic       LowCardinality(String),
            CreatedTime      DateTime64(9, 'Europe/Prague'),
            GpsTime          DateTime64(9, 'Europe/Prague'),
            GsmSignal        UInt8,
            SatelliteCount   UInt16,
            LicensePlate     String,
            VehicleType      UInt8,
            Company          LowCardinality(String),
            VehicleID        UInt32,
            Technology       UInt8,
            Ignition         UInt8,
            Longitude        Decimal(14,10),
            Latitude         Decimal(14,10),
            SpeedGps         Decimal32(3),
            SpeedTach        Decimal32(3),
            SpeedCan         Decimal32(3),
            TachoGps         Decimal32(3),
            TachoTach        Decimal32(3),
            ModeDrive        UInt8,
            SpreadingMode    UInt8,
            Plow             UInt8,
            Gram             Int32,
            WidthLeft        Decimal32(3),
            WidthRight       Decimal32(3),
            SumSalt          Decimal64(8),
            SumInert         Decimal64(8),
            SumBrine         Decimal64(8),
            Cuts1            UInt8,
            Cuts2            UInt8,
            Cuts3            UInt8,
            CentralBroom     UInt8,
            LeftBroom        UInt8,
            RightBroom       UInt8,
            Turbine          UInt8,
            RunningShaft     UInt8,
            LeftFlushing     UInt8,
            RightFlushing    UInt8,
            CentralFlushing  UInt8,
            Misting          UInt8,
            Pump             UInt8,
            LightOn          UInt8,
            ModeArrow        UInt8,
            AkuVoltage       Decimal32(3),
            RampUp           UInt8,
            Crash            UInt8,
            TempAir          Decimal32(3),
            TempRoad         Decimal32(3),
            Revs             Decimal64(10),
            RevsExtension    UInt8,
            Fuel             Decimal32(3),
            LevelPHM         Decimal32(3),
            PowerVoltage     Decimal32(3),
            Lighthouse       UInt8
        )
        ENGINE = {{ db_engine }}
        ORDER BY (VehicleID, GpsTime)
        PARTITION BY toDate(GpsTime)
        PRIMARY KEY (VehicleID, GpsTime)"
      args:
        executable: /bin/bash
      changed_when: true

    - name: Copy data
      ansible.builtin.copy:
        src: "{{ ansible_data_dir }}/{{ data_gz }}"
        dest: "{{ import_dir }}/{{ data_gz }}"
        mode: "0644"

    - name: Import data
      ansible.builtin.shell: |
        /usr/bin/time -f "DURATION_SECONDS=%e" \
        clickhouse-client \
          -q "INSERT INTO {{ db_table }} FORMAT CSVWithNames COMPRESSION 'gzip'" \
          < {{ import_dir }}/{{ data_gz }}
      args:
        executable: /bin/bash
      register: insert_time
      changed_when: true

    - name: Remove data file
      ansible.builtin.file:
        path: "{{ import_dir }}/{{ data_file }}"
        state: absent

- name: Verify data import
  hosts: clickhousedb
  tasks:
    - name: Query total SumSalt
      ansible.builtin.shell: |
        clickhouse-client -q "SELECT sum(SumSalt) FROM {{ db_table }}"
      register: query_result
      changed_when: false

    - name: Capture result
      ansible.builtin.set_fact:
        result: "{{ query_result.stdout_lines[0] | float }}"

    - name: Display total SumSalt
      ansible.builtin.debug:
        msg: "{{ result }}"

- name: Post processing
  hosts: clickhousedb
  tasks:
    - name: Common post processing
      ansible.builtin.include_tasks: "{{ ansible_common_dir }}/init/vm_post_processing.yml"
