---
- name: Delete LXD instance(s) if exists
  community.general.lxd_container:
    name: "{{ inventory_hostname }}"
    state: absent
    type: "{{ lxd_container_type | default('virtual-machine') }}"
  delegate_to: localhost

- name: Create LXD instance(s)
  community.general.lxd_container:
    name: "{{ inventory_hostname  }}"
    ignore_volatile_options: true
    type: "{{ lxd_container_type | default('virtual-machine') }}"
    state: started
    source:
      type: image
      mode: pull
      server: "{{ lxd_image_src }}"
      protocol: simplestreams
      alias: "{{ lxd_image  }}"
    profiles: "{{ lxd_profiles | default([]) }}"
    config:
      limits.memory: "{{ ram_limit }}"
      limits.cpu: "{{ cpu_limit }}"
      user.user-data: "{{ lookup('template', 'user-data.yml.j2') }}"
    devices: "{{ lxd_container_devices }}"
    wait_for_ipv4_addresses: "{{ lxd_wait_for_ipv4 | default(true) }}"
    timeout: "{{ lxd_timeout | default(120) }}"
  delegate_to: localhost

- name: Wait for SSH to become available
  ansible.builtin.wait_for_connection:
    timeout: "{{ lxd_ssh_timeout | default(120) }}"