---
- name: Get CPU and RAM profiles
  ansible.builtin.include_tasks: "include_profiles.yml"

- block:
    - name: Create LXD VM
      ansible.builtin.include_tasks: "create_vm.yml"

    - name: Setup VM 
      ansible.builtin.include_tasks: "vm_config.yml"
  when: create | default(true)

- name: Start VM
  ansible.builtin.include_tasks: "start_vm.yml"
  when: not create | default(false)

# - name: Get VM IP Address
#   ansible.builtin.include_tasks: "get_ip.yml"
#   vars:
#     max_attempts: 6
#     retry_delay: 5

# - name: Wait for SSH to be available
#   ansible.builtin.wait_for:
#     host: "{{ vm_ip }}"
#     port: 22
#     timeout: 300
#     delay: 5
#   delegate_to: localhost


