---
- name: Get query duration
  block:
  - name: Get duration from stderr
    ansible.builtin.set_fact:
      insert_duration_seconds: >-
        {{
          (
            insert_time.stderr_lines
            | select("match", "^DURATION_SECONDS=")
            | list
            | first
          )
          .split("=")[1]
          | float
        }}
    when: insert_duration_seconds is not defined and insert_time is defined
    
- name: Save result if in master run
  when: is_master_run | default(false)
  block:
    - name: Set local result fact on each host
      ansible.builtin.set_fact:
        local_result:
          test_type: "{{ test_type }}"
          host: "{{ inventory_hostname }}"
          datetime: "{{ ansible_date_time.iso8601 }}"
          sum_salt: "{{ result }}"
          insert_duration_seconds: "{{ insert_duration_seconds }}"
          ram_limit: "{{ hostvars['localhost'].ram_limit }}"
          cpu_limit: "{{ hostvars['localhost'].cpu_limit }}"

    - name: Append this host’s result to NDJSON file
      delegate_to: localhost
      ansible.builtin.lineinfile:
        path: "{{ global_results_dir | default(project_root + '/results') }}/{{ test_type }}.ndjson"
        create: true
        insertafter: EOF
        line: "{{ local_result | to_json }}"

- name: Stop VM
  community.general.lxd_container:
    name: "{{ vm_name }}"
    state: stopped
  failed_when: false
  changed_when: false
  delegate_to: localhost
