---
- block:
    - name: Start LXD VM
      community.general.lxd_container:
        name: "{{ inventory_hostname }}"
        state: started
        type: "{{ lxd_container_type | default('virtual-machine') }}"
      delegate_to: localhost

    - name: Wait for SSH to become available
      ansible.builtin.wait_for_connection:
        timeout: "{{ lxd_ssh_timeout | default(120) }}"

  rescue:
    - name: Failed to start VM, creating VM instead
      ansible.builtin.include_tasks: "create_vm.yml"
    
    - name: Setup VM 
      ansible.builtin.include_tasks: "vm_config.yml"