---
- name: Init TimescaleDB VM
  hosts: localhost
  vars_files:
    - "{{ ansible_vars_dir }}/host_vars/timescaledb.yml"
  tasks:
    - name: Init VM
      ansible.builtin.include_tasks: "{{ ansible_common_dir }}/init/vm_init.yml"

- name: Common config
  hosts: timescaledb
  tasks:
    - name: Common VM Config
      ansible.builtin.include_tasks: "{{ ansible_common_dir }}/init/vm_config.yml"

- name: Install and configure TimescaleDB
  hosts: timescaledb
  tasks:
    - name: Download TimescaleDB GPG key
      ansible.builtin.apt_key:
        url: "{{ gpg_key_url }}"
        keyring: /usr/share/keyrings/timescaledb-archive-keyring.gpg
        state: present
        validate_certs: yes

    - name: Add TimescaleDB APT repository
      ansible.builtin.apt_repository:
        repo: >
          deb [signed-by=/usr/share/keyrings/timescaledb-archive-keyring.gpg]
          https://packagecloud.io/timescale/timescaledb/ubuntu/ {{ ansible_lsb.codename }} main
        filename: timescaledb.list
        state: present
        update_cache: true

    - name: Add PostgreSQL repository
      ansible.builtin.command:
        cmd: /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh -y
      changed_when: true

    - name: Install PostgreSQL dependencies
      ansible.builtin.apt:
        name: postgresql-server-dev-17
        state: present
        update_cache: true

    - name: Install TimescaleDB
      ansible.builtin.apt:
        name:
          - timescaledb-2-postgresql-17
          - postgresql-client-17
        state: present
        update_cache: true

    - name: Tune TimescaleDB configuration
      ansible.builtin.command:
        cmd: timescaledb-tune --yes
      changed_when: true

    - name: Configure PostgreSQL authentication
      ansible.builtin.replace:
        path: /etc/postgresql/17/main/pg_hba.conf
        regexp: "{{ item.regex }}"
        replace: "{{ item.replace }}"
        backup: true
      loop:
        - regex: '^local\s+all\s+all\s+peer'
          replace: "local all all trust"
        - regex: '^host\s+all\s+all\s+127\.0\.0\.1\/32\s+scram-sha-256'
          replace: "host all all 127.0.0.1/32 trust"
        - regex: '^host\s+all\s+all\s+::1\/128\s+scram-sha-256'
          replace: "host all all ::1/128 trust"
      loop_control:
        label: "{{ item.regex }}"
      tags:
        - postgresql

    - name: Restart PostgreSQL
      ansible.builtin.systemd:
        name: postgresql
        state: restarted

- name: Setup database and import data
  hosts: timescaledb
  tasks:
    - name: Create TimescaleDB extension
      become: true
      become_user: "{{ db_user }}"
      community.postgresql.postgresql_ext:
        name: timescaledb
        login_db: "{{ login_db }}"

    - name: Create table
      become: true
      become_user: "{{ db_user }}"
      community.postgresql.postgresql_query:
        login_db: "{{ login_db }}"
        query: |
          CREATE TABLE {{ collection }} (
            orig_id INTEGER,
            orig_time TIMESTAMPTZ,
            orig_topic TEXT,
            createdtime TIMESTAMPTZ,
            gpstime TIMESTAMPTZ NOT NULL,
            gsmsignal SMALLINT,
            satellitecount SMALLINT,
            licenseplate TEXT,
            vehicletype SMALLINT,
            company TEXT,
            vehicleid INTEGER,
            technology SMALLINT,
            ignition SMALLINT,
            longitude DECIMAL(9,5),
            latitude DECIMAL(8,5),
            speedgps DECIMAL(6,2),
            speedtach DECIMAL(6,2),
            speedcan DECIMAL(6,2),
            tachogps DECIMAL(6,2),
            tachotach DECIMAL(6,2),
            modedrive SMALLINT,
            spreadingmode SMALLINT,
            plow SMALLINT,
            gram INTEGER,
            widthleft DECIMAL(4,2),
            widthright DECIMAL(4,2),
            sumsalt DOUBLE PRECISION,
            suminert DOUBLE PRECISION,
            sumbrine DOUBLE PRECISION,
            cuts1 SMALLINT,
            cuts2 SMALLINT,
            cuts3 SMALLINT,
            centralbroom SMALLINT,
            leftbroom SMALLINT,
            rightbroom SMALLINT,
            turbine SMALLINT,
            runningshaft SMALLINT,
            leftflushing SMALLINT,
            rightflushing SMALLINT,
            centralflushing SMALLINT,
            misting SMALLINT,
            pump SMALLINT,
            lighton SMALLINT,
            modearrow SMALLINT,
            akuvoltage DECIMAL(4,2),
            rampup SMALLINT,
            crash SMALLINT,
            tempair DECIMAL(6,2),
            temproad DECIMAL(5,2),
            revs DOUBLE PRECISION,
            revsextension INTEGER,
            fuel DECIMAL(6,2),
            levelphm DECIMAL(6,2),
            powervoltage DECIMAL(5,2),
            lighthouse SMALLINT
          );

    - name: Convert table to hypertable
      become: true
      become_user: "{{ db_user }}"
      ansible.builtin.command:
        argv:
          - psql
          - -d
          - "{{ login_db }}"
          - -c
          - "SELECT create_hypertable('{{ collection }}', 'gpstime');"
      changed_when: true

    - name: Push and extract data
      ansible.builtin.unarchive:
        src: "{{ ansible_data_dir }}/{{ data_tar }}"
        dest: "/tmp/"
        mode: "0777"

    - name: Import data
      become: true
      become_user: "{{ db_user }}"
      ansible.builtin.shell: |
        /usr/bin/time -f "DURATION_SECONDS=%e" \
        psql -d {{ login_db }} -c "\
          COPY {{ collection }} FROM '/tmp/{{ data_file }}' WITH (FORMAT csv, HEADER true);\
        "
      args:
        executable: /bin/bash
      register: insert_time
      changed_when: true

    - name: Remove data file
      ansible.builtin.file:
        path: /tmp/{{ data_file }}
        state: absent

- name: Verify data import
  hosts: timescaledb
  tasks:
    - name: Query total SumSalt
      become: true
      become_user: "{{ db_user }}"
      community.postgresql.postgresql_query:
        login_db: "{{ login_db }}"
        query: "SELECT sum(sumsalt) FROM {{ collection }};"
      register: query_result

    - name: Capture result
      ansible.builtin.set_fact:
        result: "{{ query_result.query_result[0].sum }}"

    - name: Display result
      ansible.builtin.debug:
        msg: "{{ result }}"

- name: Post processing
  hosts: timescaledb
  tasks:
    - name: Common post processing
      ansible.builtin.include_tasks: "{{ ansible_common_dir }}/init/vm_post_processing.yml"
