---
# VM VARS
vm_name: mongodb
vm_packages: 
  - python3-pymongo

vm_disk_size: 8GB
vm_profiles: "{{ lxd_profiles_base }}"

# FILE VARS
data_file: "raltra.json"
data_tar: "{{ data_file }}.tar.gz"
script_file: ""

# DB VARS
gpg_key_url: "https://www.mongodb.org/static/pgp/server-8.0.asc"
db_host: localhost
db_port: 27017
db_database: raltra
db_table: car_telemetry
