---
- name: Install packages
  ansible.builtin.apt:
    name: "{{ vm_packages }}"
    cache_valid_time: "{{ apt_cache_valid_time_base }}"
    state: present
    update_cache: true
  when: vm_packages is defined and vm_packages | length > 0

- name: Download QuestDB
  ansible.builtin.get_url:
    url: "{{ db_tar_url }}"
    dest: /tmp/questdb.tar.gz
    mode: "0777"

- name: Extract QuestDB
  ansible.builtin.unarchive:
    src: /tmp/questdb.tar.gz
    dest: /root/
    remote_src: true
    creates: /root/questdb

- name: Rename QuestDB folder
  ansible.builtin.command:
    cmd: mv /root/questdb-{{  db_version }}-rt-linux-x86-64 /root/questdb
  args:
    removes: /root/questdb-{{ db_version }}-rt-linux-x86-64
    creates: /root/questdb

- name: Clean up download
  ansible.builtin.file:
    path: /tmp/questdb.tar.gz
    state: absent

- name: Configure QuestDB server.conf
  ansible.builtin.template:
    src: server.conf.j2
    dest: /root/questdb/conf/server.conf
    mode: "0644"
  notify: restart questdb

- name: Create systemd service for QuestDB
  ansible.builtin.template:
    src: questdb.service.j2
    dest: /etc/systemd/system/questdb.service
    mode: "0600"
  notify: Reload systemd

- name: Enable and start QuestDB service
  ansible.builtin.systemd:
    name: questdb
    enabled: yes
    state: started