---
- name: Install and configure QuestDB
  ansible.builtin.include_tasks: "install.yml"

- name: Setup database
  ansible.builtin.include_tasks: "setup_database.yml"

- name: Import data into QuestDB
  ansible.builtin.include_tasks: "import_data.yml"

- name: Verify data import
  ansible.builtin.include_tasks: "verify_import.yml"
