---
import_dir: "/tmp"
temp_dir: "/tmp/{{ data_file_name }}_temp"
cpu_cores: "{{ hostvars['localhost'].cpu_limit | int}}"
threads: "{{ (cpu_cores * 2) | int }}"
parallel_imports: "{{ ((cpu_cores | int) <= 2) | ternary(2, (cpu_cores | int) * 2) }}"