---
# VM VARS
vm_name: timescaledb
vm_packages: 
  - postgresql-common
  - apt-transport-https
  - lsb-release
  - software-properties-common
  - python3-psycopg2


vm_disk_size: 8GB
vm_profiles: "{{ lxd_profiles_base }}"

# FILE VARS
data_file: "raltra.csv"
data_tar: "{{ data_file }}.tar.gz"
script_file: ""

# DB VARS
gpg_key_url: "https://packagecloud.io/timescale/timescaledb/gpgkey"
db_port: 5432
db_host: localhost
db_user: postgres
db_password: quest
db_database: postgres
db_table: car_telemetry
