---
- name: Deploy processing scripts
  ansible.builtin.copy:
    src: "{{ script_file }}"
    dest: "/opt/"
    mode: "0777"

- name: Copy data
  ansible.builtin.copy:
    src: "{{ data_tar }}"
    dest: "{{ import_dir }}/{{ data_tar }}"
    mode: "0644"

- name: Extract data
  ansible.builtin.shell: |
    tar --extract --use-compress-program=pigz \
    --file="{{ import_dir }}/{{ data_tar }}" \
    --directory="{{ import_dir }}"
    rm -f "{{ import_dir }}/{{ data_tar }}"
    chmod -R 0644 "{{ import_dir }}"
  args:
    executable: /bin/bash
  changed_when: true

- name: Create required directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ temp_dir }}"
    - /tmp/failed_rows

- name: Split CSV into chunks
  ansible.builtin.shell: |
    split -l 100000 --numeric-suffixes=1 --additional-suffix=.csv \
      "{{ import_dir }}/{{ data_file }}" "{{ temp_dir }}/chunk_"
  args:
    executable: /bin/bash
  changed_when: true

- name: Get chunk files
  ansible.builtin.shell:
    cmd: "ls {{ temp_dir }}/chunk_*.csv"
  register: chunk_files
  changed_when: false

- name: Set header variable from first chunk file
  ansible.builtin.slurp:
    src: "{{ (chunk_files.stdout_lines | sort)[0] }}"
  register: header_file

- name: Decode header and get first line
  ansible.builtin.set_fact:
    header_line: "{{ (header_file.content | b64decode).split('\n')[0] }}"

- name: Add header to other chunk files
  ansible.builtin.shell: |
    echo "{{ header_line }}" | cat - {{ item }} > {{ item }}.tmp && mv {{ item }}.tmp {{ item }}
  loop: "{{ (chunk_files.stdout_lines | sort)[1:] }}"

- name: Create chunk batches for limited parallel imports
  ansible.builtin.set_fact:
    chunk_batches: "{{ chunk_files.stdout_lines | batch(parallel_imports) | list }}"