---
- name: Init ClickHouse VM
  hosts: localhost
  vars_files:
    - "{{ ansible_vars_dir }}/host_vars/clickhousedb.yml"
  tasks:
    - name: Init VM
      import_role:
        name: common

- name: Common config
  hosts: clickhousedb
  tasks:
    - name: Setup config
      import_role:
        name: common
        tasks_from: vm_config

- name: Setup Telegraf
  hosts: clickhousedb
  roles:
    - telegraf

- name: Setup ClickHouseDB
  hosts: clickhousedb
  roles:
    - clickhousedb

- name: Common config
  hosts: clickhousedb
  tasks:
    - name: Setup config
      import_role:
        name: common
        tasks_from: post_processing