---
- name: Init ColumnstoreDB VM
  hosts: localhost
  vars_files:
    - "{{ ansible_vars_dir }}/host_vars/columnstoredb.yml"
  tasks:
    - name: Init VM
      import_role:
        name: common

- name: Common config
  hosts: columnstoredb
  tasks:
    - name: Setup config
      import_role:
        name: common
        tasks_from: vm_config

- name: Setup ColumnstoreDB
  hosts: columnstoredb
  roles:
    - columnstoredb

- name: Common config
  hosts: columnstoredb
  tasks:
    - name: Setup config
      import_role:
        name: common
        tasks_from: post_processing