---
- name: Setup IoTDB
  hosts: iotdb
  gather_facts: false
  roles:
    - common

    - role: telegraf
      become: true

    - role: iotdb
      become: true

  post_tasks:
    - name: Stop VM
      community.general.lxd_container:
        name: "{{ inventory_hostname }}"
        state: stopped
        type: "{{ lxd_type_base | default('virtual-machine') }}"
      failed_when: false
      changed_when: false
      delegate_to: localhost