---
- name: Setup OpenTSDB
  hosts: opentsdb
  gather_facts: false
  roles:
    - telegraf
    - opentsdb

  post_tasks:
    - name: Stop VM
      community.general.lxd_container:
        name: "{{ vm_name }}"
        state: stopped
        type: "{{ lxd_type_base }}"
      failed_when: false
      changed_when: false
      delegate_to: localhost