- name: Ensure /etc/apt/keyrings directory exists
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download InfluxData GPG key
  ansible.builtin.get_url:
    url: https://repos.influxdata.com/influxdata-archive.key
    dest: /tmp/influxdata-archive.key
    mode: '0644'

- name: Verify GPG key fingerprint
  ansible.builtin.command: >
    gpg --show-keys --with-fingerprint --with-colons /tmp/influxdata-archive.key
  register: gpg_output
  changed_when: false

- name: Fail if GPG fingerprint does not match
  ansible.builtin.fail:
    msg: "GPG key fingerprint mismatch!"
  when: "'24C975CBA61A024EE1B631787C3D57159FC2F927' not in gpg_output.stdout"

- name: Convert GPG key to keyring and save
  ansible.builtin.command: >
    gpg --dearmor --output /etc/apt/keyrings/influxdata-archive.gpg /tmp/influxdata-archive.key
  args:
    creates: /etc/apt/keyrings/influxdata-archive.gpg

- name: Add InfluxData repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/influxdata-archive.gpg] https://repos.influxdata.com/debian stable main"
    filename: influxdata
    state: present
    update_cache: yes
  register: repo_result
  retries: 5
  delay: 10
  until: repo_result is succeeded

- name: Install Telegraf
  ansible.builtin.apt:
    name: telegraf
    state: present
    update_cache: true
    install_recommends: false
    lock_timeout: 300
  retries: 5
  delay: 10
  until: result is succeeded
  register: result

- name: Read .env file content
  set_fact:
    env_file_content: "{{ lookup('file', ansible_env_file) }}"
  no_log: true

- name: Extract INFLUX_TOKEN from .env
  set_fact:
    INFLUXDB3_AUTH_TOKEN: "{{ env_file_content | regex_search('INFLUX_TOKEN=([^\n\r]*)', '\\1') | first | trim }}"
  no_log: true

- name: Copy Telegraf configuration
  ansible.builtin.template:
    src: telegraf.conf.j2
    dest: /etc/telegraf/telegraf.conf
    owner: telegraf
    group: telegraf
    mode: '0644'
  vars:
    influx_token: "{{ INFLUXDB3_AUTH_TOKEN }}"

# - name: Enable and start Telegraf
#   ansible.builtin.service:
#     name: telegraf
#     state: started
#     enabled: yes