---
- name: Get Query timing
  block:
  - name: Increment attempts counter
    ansible.builtin.set_fact:
      attempt_number: "{{ attempt_number | d(0) | int + 1 }}"

  - name: Capture query timing
    ansible.builtin.shell: |
      clickhouse-client \
        --query="
          SELECT 
            query_duration_ms,
            read_rows,
            result_rows
          FROM system.query_log
          WHERE type = 'QueryFinish'
            AND query LIKE '%VehicleID = ''{{ vehicle_id }}''%'
            AND query LIKE '%GpsTime = toDateTime(''{{ target_timestamp }}'')%'
          ORDER BY event_time DESC
          LIMIT 1"
    register: timing_results
    changed_when: false

  - name: Parse latency metrics
    ansible.builtin.set_fact:
      latency_parts: "{{ timing_results.stdout_lines[0].split('\t') }}"

  - name: Extract individual metrics as facts
    ansible.builtin.set_fact: 
      query_duration_ms: "{{ (latency_parts[0] | float ) * 0.001}}"
      rows_read: "{{ latency_parts[1] | int }}"
      rows_returned: "{{ latency_parts[2] | int }}"
  
  rescue:
    - name: "Fail if we reached the max of {{ max_attempts | d(3) }} attempts"
      ansible.builtin.fail:
        msg: Maximum number of attempts reached
      when: attempt_number | int == max_attempts | int | d(3)

    - name: Show number of attempts
      ansible.builtin.debug:
        msg: "group of tasks failed on attempt {{ attempt_number }}. Retrying"

    - name: Add delay if configured
      ansible.builtin.wait_for:
        timeout: "{{ retry_delay | int | d(omit) }}"
      when: retry_delay is defined

    - name: Include ourselves to retry.
      ansible.builtin.include_tasks: get_query_timing.yml
